config/routes.rb
CustomerPortal::Application.routes.draw do

  devise_for :subscriber_users, :controllers => {
      :sessions => "subscriber_users/sessions",
      :confirmation => "subscriber_users/confirmations",
      :passwords => "subscriber_users/passwords",
      :registrations => "subscriber_users/registrations",
      :unlocks => "subscriber_users/unlocks",
      :omniauth => "subscriber_users/omniauth_callbacks"
  }

  devise_for :subscriber_users
  as :subscriber_user do
    root :to => 'subscriber_users/sessions#new'
    get 'subscriber' => 'subscriber_users/sessions#new', :as => :new_user_session
    post 'subscriber' => 'subscriber_users/sessions#create', :as => :user_session
    get 'sign_up' => 'subscriber_users/registrations#new', :as => :user_session
    get "sign_out" => "subscriber_users/sessions#destroy"
  end

  resources :reportings do
    collection do
      get :search_cdr
      post :export_cdr
    end
  end

end

app/views/shared/_active_ports.html.erb
<!--<div style="float: left; width: 100%;">-->
<!--<p>Active Ports</p>-->
<!--<span>-->
<%#= @active_ports.blank? ? 0 : @active_ports %>
<!--</span>-->
<!--</div>-->

<!--<div style="float: left; width: 100%;">-->
<!--<p class="p-style">Enabled Ports</p><span> <%#= current_user.ports_order unless current_user.blank? %> </span>-->
<!--</div>-->
<div id="gauge_div" style="float: left; margin-left: 45px;">

</div>

<script type='text/javascript'>
    $(document).ready(function () {
        drawChart();
    });
    function drawChart() {
        var active_ports = '<%=@active_ports%>';
        var max_ports = <%= current_subscriber_user.ports_order unless current_subscriber_user.blank? %>;
        var min_val = (max_ports / 100) * 80;
        var max_val = (max_ports / 100) * 90;
        if (active_ports == "") {
            active_ports = 0;
        }
        var data = google.visualization.arrayToDataTable([
            ['Label', 'Value'],
            ['Active Ports', parseInt(active_ports)]
        ]);

        var options = {
            width:600, height:130,
            min:0,
            yellowFrom:min_val, yellowTo:max_val,
            redFrom:max_val, redTo:max_ports,
            max:max_ports
        };

        var chart = new google.visualization.Gauge(document.getElementById('gauge_div'));
        chart.draw(data, options);
    }
</script>

app/views/shared/_bred_crumbs.html.erb
<artical id="basic-tab">
  <% if params[:controller] == "dashboard" and params[:action] == "index" %>
      <div class="tabs">
        <%= link_to "Dashboard", "/dashboard" %>
      </div>
  <% elsif params[:controller] == "mycarriers" and params[:action] == "new" %>
      <div class="tabs">
        <%= link_to "Carrier", "/mycarriers/show" %>
      </div>
      <div class="tabs-3">
        <%= link_to "New Carriers", "/mycarriers/new" %>
      </div>
  <% elsif params[:controller] == "mycarriers" and params[:action] == "edit" %>
      <div class="tabs">
        <%= link_to "Carrier", "/mycarriers/show" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Manage Carriers", "/mycarriers/#{request.url.to_s.split("/edit").first.split("mycarriers/").last}/edit" %>
      </div>
  <% elsif params[:controller] == "mycarriers" and params[:action] == "show" %>
      <div class="tabs">
        <%= link_to "Carrier", "/mycarriers/show" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Display Carriers", "/mycarriers/show" %>
      </div>
  <% elsif params[:controller] == "mycarriers" and params[:action] == "code_list" %>
      <div class="tabs">
        <%= link_to "Carrier", "/mycarriers/show" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Master Code List", "/mycarriers/code_list" %>
      </div>

  <% elsif params[:controller] == "trunk_groups" and params[:action] == "index" %>
      <div class="tabs">
        <%= link_to "Trunk Groups", "/trunk_groups" %>
      </div>
      <div class="tabs-3">
        <%= link_to "DisplayTrunkGroups", "/trunk_groups" %>
      </div>

  <% elsif (params[:controller] == "trunk_groups" and params[:action] == "new") or (params[:controller] == "trunk_groups" and params[:action] == "create") %>
      <div class="tabs">
        <%= link_to "Trunk Groups", "/trunk_groups" %>
      </div>
      <div class="tabs-3">
        <%= link_to "NewTrunkGroup", "/trunk_groups/new" %>
      </div>
  <% elsif (params[:controller] == "trunk_groups" and params[:action] == "edit") or (params[:controller] == "trunk_groups" and params[:action] == "update") %>
      <div class="tabs">
        <%= link_to "Trunk Groups", "/trunk_groups" %>
      </div>
      <div class="tabs-3">
        <%= link_to "MangeTrunkGroup", "/trunk_groups/#{request.url.to_s.split("/edit").first.split("trunk_groups/").last}/edit" %>
      </div>
  <% elsif params[:controller] == "administrator" and params[:action] == "index" %>
      <div class="tabs">
        <%= link_to "Administrators", "/administrator" %>
      </div>

  <% elsif params[:controller] == "administrator" and params[:action] == "send_message" %>
      <div class="tabs">
        <%= link_to "Support", "/administrator/send_message" %>
      </div>
  <% elsif params[:controller] == "administrator" and params[:action] == "setting_page" %>
      <div class="tabs">
        <%= link_to "Settings", "/administrator/setting_page" %>
      </div>
  <% elsif params[:controller] == "routings" and params[:action] == "block_lists" %>
      <div class="tabs">
        <%= link_to "Routing", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Block List", "/routings/block_lists" %>
      </div>
  <% elsif params[:controller] == "routings" and params[:action] == "mange_routing" %>
      <div class="tabs">
        <%= link_to "Routing", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Mange Routing", "/routings/mange_routing" %>
      </div>
  <% elsif params[:controller] == "sales" and params[:action] == "originator_sheet" %>
      <div class="tabs">
        <%= link_to "Sales", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Originator RateSheet", "/sales/originator_sheet" %>
      </div>
  <% elsif params[:controller] == "sales" and params[:action] == "terminator_sheet" %>
      <div class="tabs">
        <%= link_to "Sales", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Terminator RateSheet", "/sales/terminator_sheet" %>
      </div>

  <% elsif params[:controller] == "accountings" and params[:action] == "generate_invoice" %>
      <div class="tabs">
        <%= link_to "Accounting", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Generate Invoice", "/accountings/generate_invoice" %>
      </div>
  <% elsif params[:controller] == "accountings" and params[:action] == "record_payment" %>
      <div class="tabs">
        <%= link_to "Accounting", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Record Payment", "/accountings/record_payment" %>
      </div>
  <% elsif params[:controller] == "accountings" and params[:action] == "financial_reports" %>
      <div class="tabs">
        <%= link_to "Accounting", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Financial Reports", "/accountings/financial_reports" %>
      </div>
  <% elsif params[:controller] == "reportings" and params[:action] == "daily_originator_report" %>
      <div class="tabs">
        <%= link_to "Reporting", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Originator Reports", "/reportings/daily_originator_report" %>
      </div>
  <% elsif params[:controller] == "reportings" and params[:action] == "daily_terminator_report" %>
      <div class="tabs">
        <%= link_to "Reporting", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Terminator Reports", "/reportings/daily_terminator_report" %>
      </div>
  <% elsif params[:controller] == "reportings" and params[:action] == "search_cdr" %>
      <div class="tabs">
        <%= link_to "Reporting", "javascript:void(0);" %>
      </div>
      <div class="tabs-3">
        <%= link_to "Diagnostics", "/reportings/search_cdr" %>
      </div>
  <% elsif params[:controller] == "audit_logs" and params[:action] == "index" %>
      <div class="tabs">
        <%= link_to "Audit Logs", "/audit_logs" %>
      </div>
  <% end %>


</artical>

app/views/shared/_flash.html.erb
<% [:alert, :notice, :error].select { |type| !flash[type].blank? }.each do |type| %>
    <div id="flash_notices">
      <div id="content" style="padding: 0 440px;">
        <% if flash[:notice] %>
            <div class="message success"><p>
              <%= flash[type] %>
            </p>
            </div>
        <% elsif flash[:error] %>
            <div class="message errormsg"><p>
              <% flash[:error].each_with_index do |error, index| %>
                  <%= error %> <br/>
              <% end %>
            </p>
            </div>
        <% elsif  flash[:alert] %>
            <div class="message warning"><p>
              <%= flash[type] %>
            </p>
            </div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_flash_user.html.erb
<% [:alert, :notice, :error, :errormsg].select { |type| !flash[type].blank? }.each do |type| %>
    <div id="flash_notices">
      <div id="content" style="padding: 0 223px;">
        <% if flash[:notice] %>
            <div class="message success">
              <p>
                <%= flash[type] %>
              </p>
            </div>
        <% elsif flash[:error] %>
            <div class="message errormsg">
              <p>
                <% flash[:error].each_with_index do |error, index| %>
                    <%= error %> <br/>
                <% end %>
              </p>
            </div>
        <% elsif  flash[:alert] %>
            <div class="message warning">
              <p>
                <%= flash[type] %>
              </p>
            </div>
        <% elsif  flash[:errormsg] %>
            <div class="message errormsg">
              <p>
                <%= flash[type] %>
              </p>
            </div>
        <% end %>

      </div>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<script type='text/javascript' src='https://www.google.com/jsapi'></script>

<script type="text/javascript">
    google.load('visualization', '1', {packages:['gauge']});
    var button_timer = "";
</script>
<section id="sys-active-enable-ports">
  <div class="sys-time">
    <p>System Time</p>

    <div class="clock">
      <div id="Date"></div>
      <ul class="sys-time-detail">
        <li id="hours"></li>
        <li id="point">:</li>
        <li id="min"></li>
        <li id="point">:</li>
        <li id="sec"></li>
      </ul>
    </div>
  </div>
  <div id="timer"></div>
  <div class="small-seperator"></div>

  <div class="sys-time-2"><%= render :partial => "shared/active_ports" %></div>

  <div class="small-seperator"></div>

  <div class="sys-time-3">
    <div class="update-switch">
      <%= submit_tag "UPDATE SWITCH", :id => "u_switch" %>
    </div>
  </div>


</section>
<section id="switch" style="display: none;">
</section>

<footer>
  <p><%= "Copyright 2012. 46 Labs, LLC ~ VERSION "+APP_VERSION %></p>
</footer>


<script type="text/javascript">
    var d;
    $(document).ready(function () {
        // Create two variable with the names of the months and days in an array
        var monthNames = [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ];
        var dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

        // Create a newDate() object
        var newDate = new Date();
        // Extract the current date from Date object
        newDate.setDate(newDate.getUTCDate());
        // Output the day, date, month and year
        $('#Date').html(dayNames[newDate.getUTCDay()] + " " + newDate.getUTCDate() + ' ' + monthNames[newDate.getUTCMonth()] + ' ' + newDate.getFullYear());

        setInterval(function () {
            // Create a newDate() object and extract the seconds of the current time on the visitor's
            var seconds = new Date().getUTCSeconds();
            // Add a leading zero to seconds value
            $("#sec").html(( seconds < 10 ? "0" : "" ) + seconds);
        }, 1000);

        setInterval(function () {
            // Create a newDate() object and extract the minutes of the current time on the visitor's
            var minutes = new Date().getUTCMinutes();
            // Add a leading zero to the minutes value
            $("#min").html(( minutes < 10 ? "0" : "" ) + minutes);
        }, 1000);

        setInterval(function () {
            // Create a newDate() object and extract the hours of the current time on the visitor's
            var hours = new Date().getUTCHours();
            // Add a leading zero to the hours value
            $("#hours").html(( hours < 10 ? "0" : "" ) + hours);
        }, 1000);
        clearTimeout(button_timer);
        d = setInterval("refresh_active_ports()", 300000);
    });

    $("#u_switch").click(function (e) {
        apprise("Update Switch may only be selected once in a 5-minute period", {'confirm':true}, function (r) {
            if (r) {
                $('.shadow').show();
                $("#switch").show();
                $("#switch").load('/opensips/update_switch_status');
                setTimeout(clean_tables, 2000)
            }
        });

    });

    function clean_tables() {
        $.ajax({
            url:'/opensips/clean_tables',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d1').removeClass("switch_running");
                    $('#d1').addClass("switch_complete");
                    $('#s1').html("Complete");
                    setTimeout(cache_trunks, 2000)
                }
                else if (data == "failed") {
                    $('#d1').removeClass("switch_running");
                    $('#d1').addClass("switch_failed");
                    $('#s1').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s1').css("color", "#E51414");
                }
            }
        });
    }

    function cache_trunks() {
        $.ajax({
            url:'/opensips/build_trunks',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d2').removeClass("switch_running");
                    $('#d2').addClass("switch_complete");
                    $('#s2').html("Complete");
                    setTimeout(build_routes, 2000)
                }
                else if (data == "failed") {
                    $('#d2').removeClass("switch_running");
                    $('#d2').addClass("switch_failed");
                    $('#s2').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s2').css("color", "#E51414");
                }
            }
        });
    }

    function build_routes() {
        $.ajax({
            url:'/opensips/build_routes',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d3').removeClass("switch_running");
                    $('#d3').addClass("switch_complete");
                    $('#s3').html("Complete");
                    setTimeout(create_blocklist, 1000)
                }
                else if (data == "failed") {
                    $('#d3').removeClass("switch_running");
                    $('#d3').addClass("switch_failed");
                    $('#s3').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s3').css("color", "#E51414");
                }
            }
        });

    }

    function create_blocklist() {
        $.ajax({
            url:'/opensips/create_block_list',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d4').removeClass("switch_running");
                    $('#d4').addClass("switch_complete");
                    $('#s4').html("Complete");
                    setTimeout(reload_tables, 1000)
                }
                else if (data == "failed") {
                    $('#d4').removeClass("switch_running");
                    $('#d4').addClass("switch_failed");
                    $('#s4').html("Failed");
                    $('#s4').css("color", "#E51414");
                    $('#dismiss_btn').show();
                }
            }
        });


    }

    function reload_tables() {
        $.ajax({
            url:'/opensips/reload_tables',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d5').removeClass("switch_running");
                    $('#d5').addClass("switch_complete");
                    $('#s5').html("Complete");
                    $('#dismiss_btn').show();
                }
                else if (data == "failed") {
                    $('#d5').removeClass("switch_running");
                    $('#d5').addClass("switch_failed");
                    $('#s5').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s5').css("color", "#E51414");
                }
            }
        });
    }

    function refresh_active_ports() {

        var container = $(".sys-time-2");
        $.ajax({
            url:'/dashboard/refresh_active_ports',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                container.html(data);
            },
            error:function (data) {
                window.location.reload();
            }
        });

    }

</script>

app/views/shared/_header.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        $('ul.sf-menu').superfish({
            delay:500, // one second delay on mouseout
            animation:{opacity:'show'}, // fade-in and slide-down animation
            speed:'fast', // faster animation speed
            autoArrows:false, // disable generation of arrow mark-up
            dropShadows:false                            // disable drop shadows
        });
    });

</script>
<div id="flash1">
  <%= render :partial => 'shared/flash', :object => flash %>
</div>
<header>
  <section>
    <div id="rightLinks">
      <div class="right">
        <div class="link"><a href="javascript:;"></a><span></span></div>
        <div class="link"><%= link_to @current_user.username.upcase, "javascript:;" unless @current_user.blank? %>
          <span>|</span></div>
        <div class="drop-link"><a href="/sign_out">Logout</a>
          <span></span></div>
      </div>
    </div>
    <figure><img src="/assets/pr_images/1.png"></figure>

    <artical id="right-search">
      <search id="search-input"/>
    </artical>
    <%= render :partial => "shared/bred_crumbs" %>
  </section>
</header>
<section>


</section>

app/views/shared/_main_container.html.erb
<div class="leftContainer">

  <div class="demo">
    <div class="main-rect-container">
      <h1>Subscriber</h1>

      <div class="main-rect-detail">
        <p><%= current_user.subscriber.blank? ? current_user.email : current_user.subscriber %></p></div>

    </div>

    <div id="linkGuide" class="link-guide">
      <p><%= link_to 'Customer Portal' %> > <%= link_to "DashBoard" %>  </p>

    </div>
    <div id="accordionResizer" style="padding:10px; width:200px; height:400px;" class="ui-widget-content">

      <div id="accordion">
        <h3><a href="#">DashBoard</a></h3>

        <div>
          <p><%= link_to 'Main', "/dashboard" %></p>
        </div>
        <h3><a href="#">Carriers</a></h3>

        <div>
          <p><%= link_to 'Add Carriers', "/mycarriers/new" %></p>

          <p><%= link_to 'Display Carriers', "/mycarriers/show" %></p>

          <p><%= link_to 'Add Trunkgroup', "/trunk_groups/new" %></p>

          <p><%= link_to 'Display Trunkgroup', "/trunk_groups" %></p>

          <p><%= link_to 'Master CodeList', "/mycarriers/code_list" %></p>

        </div>
        <h3><a href="#">Sales</a></h3>

        <div>
          <p><%= link_to 'Originator Ratesheet', "/sales/originator_sheet" %></p>

          <p><%= link_to 'Terminator Ratesheet', "/sales/terminator_sheet" %></p>

        </div>

        <h3><a href="#">Routing</a></h3>

        <div>
          <p><%= link_to 'Blacklists', "/routings/black_lists" %></p>

          <p><%= link_to 'Manage Routing', "/routings/mange_routing" %></p>

        </div>
        <h3><a href="#">Accounting</a></h3>

        <div>
          <p><%= link_to 'Generate Invoice', "/accountings/generate_invoice" %></p>

          <p><%= link_to 'Record Payment', "/accountings/record_payment" %></p>

          <p><%= link_to 'Financial Reports', "/accountings/financial_reports" %></p>
        </div>
        <h3><a href="#">Reporting</a></h3>

        <div>
          <p><%= link_to 'Terminators', '/reportings/daily_terminator_report' %></p>

          <p><%= link_to 'Originators', '/reportings/daily_originator_report' %></p>

          <p><%= link_to 'Search CDR', '/reportings/search_cdr' %></p>
        </div>
        <h3><a href="#">Administration</a></h3>

        <div>
          <p><%= link_to 'Administrators', '/administrator' %></p>

          <p><%= link_to 'Audit Log', '/subscriber_audit_logs' %></p>

          <p><%= link_to 'Support', '/administrator/send_message' %></p>

          <p><%= link_to 'Settings', '/administrator/index' %></p>
        </div>
      </div>


      <span class="ui-icon ui-icon-grip-dotted-horizontal" style="margin:2px auto;"></span>
    </div>

  </div>

  <div class="time-rect-container">

    <%= render :partial => 'shared/time_portion' %>


  </div>
  <div class="active-port">
    <h1>Active Ports</h1>

    <div class="active-port-detail"><p>0</p></div>

  </div>

  <div class="enabled-port">
    <h1>Enabled Ports</h1>
    <% ports = 0 %>
    <div class="enabled-port-detail">
      <p><%= ports = current_user.ports_order unless current_user.ports_order.blank? %></p></div>

  </div>

  <div class="enabled-port">
    <h1>Update Settings</h1>

    <div class="enabled-port-detail">
      <%= link_to "Update Switch", '/opensips/update_switch', :id => "enable1_btn", :class => "switch-action-btn" %>
    </div>

  </div>


</div>


<script type="text/javascript">
    var dashboard = "hello"
    //    $(document).ready(
    //            function () {
    //                setInterval(function () {
    //                    $('.time-rect-container').load('/dashboard/give_time');
    //                }, 1000);
    //            });
    $(function () {
        $("#accordion").accordion({
            fillSpace:true
        });
    });
    $(function () {
        $("#accordionResizer").resizable({
            minHeight:140,
            resize:function () {
                $("#accordion").accordion("resize");
            }
        });
    });

</script>

app/views/shared/_time_portion.html.erb
<h1>System Time</h1>

<div class="time-detail"><p><%=@time%></p></div>