config/routes.rb
CustomerPortal::Application.routes.draw do

  devise_for :subscriber_users, :controllers => {
      :sessions => "subscriber_users/sessions",
      :confirmation => "subscriber_users/confirmations",
      :passwords => "subscriber_users/passwords",
      :registrations => "subscriber_users/registrations",
      :unlocks => "subscriber_users/unlocks",
      :omniauth => "subscriber_users/omniauth_callbacks"
  }

  devise_for :subscriber_users
  as :subscriber_user do
    root :to => 'subscriber_users/sessions#new'
    get 'subscriber' => 'subscriber_users/sessions#new', :as => :new_user_session
    post 'subscriber' => 'subscriber_users/sessions#create', :as => :user_session
    get 'sign_up' => 'subscriber_users/registrations#new', :as => :user_session
    get "sign_out" => "subscriber_users/sessions#destroy"
  end

  resources :reportings do
    collection do
      get :search_cdr
      post :export_cdr
    end
  end

end

app/models/subscriber_user.rb
class SubscriberUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :carrier_id, :has_one, :subscriber, :username, :carrier_name

  has_many :carriers

end

app/controllers/subscriber_users/confirmations_controller.rb
class SubscriberUsers::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/subscriber_users/omniauth_callbacks_controller.rb
class SubscriberUsers::OmniauthCdestroyallbacksController < Devise::OmniauthCallbacksController

end


app/controllers/subscriber_users/passwords_controller.rb
class SubscriberUsers::PasswordsController < Devise::PasswordsController
  prepend_before_filter :require_no_authentication
  skip_before_filter :check_agreement
  # Render the #edit only if coming from a reset password email link
  append_before_filter :assert_reset_token_passed, :only => :edit

  # GET /resource/password/new
  def new
    build_resource({})
  end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)

    if successfully_sent?(resource)
      respond_with({}, :location => after_sending_reset_password_instructions_path_for(resource_name))
    else
      puts"aaaaaaaaaa",resource.inspect
      flash_message = "Invalid Email"
      set_flash_message(:errormsg, flash_message)
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)

    if resource.errors.empty?
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_navigational_format?
      sign_in(resource_name, resource)
      respond_with resource, :location => after_sign_in_path_for(resource)
    else
      respond_with resource
    end
  end

  protected

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    new_session_path(resource_name)
  end

  # Check if a reset_password_token is provided in the request
  def assert_reset_token_passed
    if params[:reset_password_token].blank?
      set_flash_message(:error, :no_token)
      redirect_to new_session_path(resource_name)
    end
  end
end

app/controllers/subscriber_users/registrations_controller.rb
class SubscriberUsers::RegistrationsController < Devise::RegistrationsController

  before_filter :authenticate_subscriber_user!

end

app/controllers/subscriber_users/sessions_controller.rb
class SubscriberUsers::SessionsController < Devise::SessionsController
  skip_before_filter :check_agreement
  layout nil

  def new
    notice = flash[:notice]
    if notice.blank?
      notice = flash[:alert]
    end
    reset_session
    unless params[:id].blank?
      user = User.find(params[:id])
      unless user.blank?
        sign_in(:user, user)
        redirect_to "/dashboard", :notice => "Signed in successfully"
        return
      end
    else
      flash[:alert] = notice
      session[:url] = request.url
      resource = build_resource
      clean_up_passwords(resource)
      respond_with(resource, serialize_options(resource))
    end
  end

  def create

      resource = warden.authenticate!(auth_options)
      set_flash_message(:notice, :signed_in) if is_navigational_format?
      sign_in(resource_name, resource)
      respond_with resource, :location => after_sign_in_path_for(resource)
    #else
    #  flash[:notice] = "Invalid email or password"
    #  redirect_to '/subscriber'
    #end
  end


  def destroy
    redirect_path = after_sign_out_path_for(resource_name)
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out

    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.any(*navigational_formats) { redirect_to redirect_path }
      format.all do
        method = "to_#{request_format}"
        text = {}.respond_to?(method) ? {}.send(method) : ""
        render :text => text, :status => :ok
      end
    end
  end

end

app/controllers/subscriber_users/unlocks_controller.rb
class SubscriberUsers::UnlocksController < Devise::UnlocksController
end

app/views/subscriber_users/shared/_flash_user.html.erb
<% [:alert, :notice, :error, :errormsg].select { |type| !flash[type].blank? }.each do |type| %>
    <div id="flash_notices">
      <div id="content" style="padding: 0 223px;">
        <% if flash[:notice] %>
            <div class="message success">
              <p>
                <%= flash[type] %>
              </p>
            </div>
        <% elsif flash[:error] %>
            <div class="message errormsg">
              <p>
                <% flash[:error].each_with_index do |error, index| %>
                    <%= error %> <br/>
                <% end %>
              </p>
            </div>
        <% elsif  flash[:alert] %>
            <div class="message warning">
              <p>
                <%= flash[type] %>
              </p>
            </div>
        <% elsif  flash[:errormsg] %>
            <div class="message errormsg">
              <p>
                <%= flash[type] %>
              </p>
            </div>
        <% end %>

      </div>
    </div>
<% end %>

app/views/subscriber_users/shared/_footer.html.erb
<script type='text/javascript' src='https://www.google.com/jsapi'></script>

<script type="text/javascript">
    google.load('visualization', '1', {packages:['gauge']});
    var button_timer = "";
</script>
<section id="sys-active-enable-ports">
  <div class="sys-time">
    <p>System Time</p>

    <div class="clock">
      <div id="Date"></div>
      <ul class="sys-time-detail">
        <li id="hours"></li>
        <li id="point">:</li>
        <li id="min"></li>
        <li id="point">:</li>
        <li id="sec"></li>
      </ul>
    </div>
  </div>
  <div id="timer"></div>
  <div class="small-seperator"></div>

  <div class="sys-time-2"><%= render :partial => "shared/active_ports" %></div>

  <div class="small-seperator"></div>

  <div class="sys-time-3">
    <div class="update-switch">
      <%= submit_tag "UPDATE SWITCH", :id => "u_switch" %>
    </div>
  </div>


</section>
<section id="switch" style="display: none;">
</section>

<footer>
  <p><%= "Copyright 2012. 46 Labs, LLC ~ VERSION "+APP_VERSION %></p>
</footer>


<script type="text/javascript">
    var d;
    $(document).ready(function () {
        // Create two variable with the names of the months and days in an array
        var monthNames = [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ];
        var dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]

        // Create a newDate() object
        var newDate = new Date();
        // Extract the current date from Date object
        newDate.setDate(newDate.getUTCDate());
        // Output the day, date, month and year
        $('#Date').html(dayNames[newDate.getUTCDay()] + " " + newDate.getUTCDate() + ' ' + monthNames[newDate.getUTCMonth()] + ' ' + newDate.getFullYear());

        setInterval(function () {
            // Create a newDate() object and extract the seconds of the current time on the visitor's
            var seconds = new Date().getUTCSeconds();
            // Add a leading zero to seconds value
            $("#sec").html(( seconds < 10 ? "0" : "" ) + seconds);
        }, 1000);

        setInterval(function () {
            // Create a newDate() object and extract the minutes of the current time on the visitor's
            var minutes = new Date().getUTCMinutes();
            // Add a leading zero to the minutes value
            $("#min").html(( minutes < 10 ? "0" : "" ) + minutes);
        }, 1000);

        setInterval(function () {
            // Create a newDate() object and extract the hours of the current time on the visitor's
            var hours = new Date().getUTCHours();
            // Add a leading zero to the hours value
            $("#hours").html(( hours < 10 ? "0" : "" ) + hours);
        }, 1000);
        clearTimeout(button_timer);
        d = setInterval("refresh_active_ports()", 300000);
    });

    $("#u_switch").click(function (e) {
        apprise("Update Switch may only be selected once in a 5-minute period", {'confirm':true}, function (r) {
            if (r) {
                $('.shadow').show();
                $("#switch").show();
                $("#switch").load('/opensips/update_switch_status');
                setTimeout(clean_tables, 2000)
            }
        });

    });

    function clean_tables() {
        $.ajax({
            url:'/opensips/clean_tables',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d1').removeClass("switch_running");
                    $('#d1').addClass("switch_complete");
                    $('#s1').html("Complete");
                    setTimeout(cache_trunks, 2000)
                }
                else if (data == "failed") {
                    $('#d1').removeClass("switch_running");
                    $('#d1').addClass("switch_failed");
                    $('#s1').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s1').css("color", "#E51414");
                }
            }
        });
    }

    function cache_trunks() {
        $.ajax({
            url:'/opensips/build_trunks',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d2').removeClass("switch_running");
                    $('#d2').addClass("switch_complete");
                    $('#s2').html("Complete");
                    setTimeout(build_routes, 2000)
                }
                else if (data == "failed") {
                    $('#d2').removeClass("switch_running");
                    $('#d2').addClass("switch_failed");
                    $('#s2').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s2').css("color", "#E51414");
                }
            }
        });
    }

    function build_routes() {
        $.ajax({
            url:'/opensips/build_routes',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d3').removeClass("switch_running");
                    $('#d3').addClass("switch_complete");
                    $('#s3').html("Complete");
                    setTimeout(create_blocklist, 1000)
                }
                else if (data == "failed") {
                    $('#d3').removeClass("switch_running");
                    $('#d3').addClass("switch_failed");
                    $('#s3').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s3').css("color", "#E51414");
                }
            }
        });

    }

    function create_blocklist() {
        $.ajax({
            url:'/opensips/create_block_list',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d4').removeClass("switch_running");
                    $('#d4').addClass("switch_complete");
                    $('#s4').html("Complete");
                    setTimeout(reload_tables, 1000)
                }
                else if (data == "failed") {
                    $('#d4').removeClass("switch_running");
                    $('#d4').addClass("switch_failed");
                    $('#s4').html("Failed");
                    $('#s4').css("color", "#E51414");
                    $('#dismiss_btn').show();
                }
            }
        });


    }

    function reload_tables() {
        $.ajax({
            url:'/opensips/reload_tables',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                if (data == "ok") {
                    $('#d5').removeClass("switch_running");
                    $('#d5').addClass("switch_complete");
                    $('#s5').html("Complete");
                    $('#dismiss_btn').show();
                }
                else if (data == "failed") {
                    $('#d5').removeClass("switch_running");
                    $('#d5').addClass("switch_failed");
                    $('#s5').html("Failed");
                    $('#dismiss_btn').show();
                    $('#s5').css("color", "#E51414");
                }
            }
        });
    }

    function refresh_active_ports() {

        var container = $(".sys-time-2");
        $.ajax({
            url:'/dashboard/refresh_active_ports',
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                container.html(data);
            },
            error:function (data) {
                window.location.reload();
            }
        });

    }

</script>

app/views/subscriber_users/shared/_header.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        $('ul.sf-menu').superfish({
            delay:500, // one second delay on mouseout
            animation:{opacity:'show'}, // fade-in and slide-down animation
            speed:'fast', // faster animation speed
            autoArrows:false, // disable generation of arrow mark-up
            dropShadows:false                            // disable drop shadows
        });
    });

</script>
<div id="flash1">
  <%= render :partial => 'shared/flash', :object => flash %>
</div>
<header>
  <section>
    <div id="rightLinks">
      <div class="right">
        <div class="drop-link"><a href="/sign_out">Logout</a>
          <span></span></div>

        <div class="link"><a href="javascript:;"></a><span></span></div>
        <div class="link"><%= link_to @current_user.user_name.upcase, "javascript:;" unless @current_user.blank? %>
          <span>|</span></div>
      </div>
    </div>
    <figure><img src="/assets/pr_images/1.png"></figure>

    <artical id="right-search">
      <search id="search-input"/>
    </artical>
    <%= render :partial => "shared/bred_crumbs" %>
  </section>
</header>
<section>

  <section id="big-tabs">

    <ul class="sf-menu">
      <li>
        <a href="/dashboard" class="<%= "current" if params[:controller] == "dashboard" %>">Dashboard</a>
      </li>
      <li>
        <a href="javascript:void(0);" class="<%= "current" if params[:controller] == "carriers" %>">Carriers</a>
        <ul>
          <li>
            <a href="/mycarriers/new">Add Carrier</a>
          </li>

          <li>
            <a href="/mycarriers/show">Display Carrier</a>
          </li>
          <li>
            <a href="/trunk_groups/new">Add Trunk Group</a>
          </li>
          <li>
            <a href="/trunk_groups">Display Trunk Group</a>
          </li>
          <li>
            <a href="/mycarriers/code_list">Master Codelist</a>
          </li>
        </ul>
      </li>

      <li>
        <a href="javascript:;" class="<%= "current" if params[:controller] == "routings" %>">Routing</a>
        <ul>
          <li>
            <a href="/routings/block_lists">Blocklist</a>
          </li>

          <li>
            <a href="/routings/mange_routing">Manage Routing</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="javascript:;" class="<%= "current" if params[:controller] == "sales" %>">Sales</a>
        <ul>
          <li>
            <a href="/sales/originator_sheet">Originator Ratesheet</a>
          </li>

          <li>
            <a href="/sales/terminator_sheet">Terminator Ratesheet</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="javascript:;" class="<%= "current" if params[:controller] == "accountings" %>">Accounting</a>
        <ul>
          <li>
            <a href="/accountings/generate_invoice">Generate Invoice</a>
          </li>

          <li>
            <a href="/accountings/record_payment">Record Payment</a>
          </li>

          <li>
            <a href="/accountings/financial_reports">Financial Reports</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="javascript:;" class="<%= "current" if params[:controller] == "reportings" %>">Reporting</a>
        <ul>
          <!--<li>-->
            <!--<a href="/reportings/daily_terminator_report">Terminators</a>-->
          <!--</li>-->
          <!--<li>-->
            <!--<a href="/reportings/daily_originator_report">Originators</a>-->
          <!--</li>-->
          <li>
            <a href="/reportings/search_cdr">Diagnostics</a>
          </li>
          <li>
            <a href="/reportings/carriers_report">Carriers</a>
          </li>
          <li>
            <a href="/reportings/country_report">Countries</a>
          </li>
          <li>
            <a href="/reportings/route_plan_report">Route Plan</a>
          </li>
          <li>
            <a href="/reportings/durations_report">Durations</a>
          </li>
        </ul>
      </li>

      <li>
        <a href="javascript:;" class="<%= "current" if params[:controller] == "administrator" %>">Admin</a>
        <ul>
          <li>
            <a href="/administrator">Administrators</a>
          </li>
          <li>
            <a href="/administrator/send_message">Support</a>
          </li>
          <li>
            <a href="/audit_logs">Audit Log</a>
          </li>
          <li>
            <a href="/administrator/setting_page">Invoice Settings</a>
          </li>
          <li>
            <a href="/administrator/payment_page">Payment</a>
          </li>
        </ul>
      </li>
    </ul>
  </section>
</section>

app/views/subscriber_users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>